version: 2.1
orbs: 
  node: 'circleci/node:4.1'
  slack: circleci/slack@4.10.1

jobs: 
  build-frontend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:      
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
            
      - save_cache: 
          paths: [frontend/node_modules]
          key: frontend-build   
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:    
          name: Back-end build  
          command: |
            cd backend
            npm install
            npm run build   
      - save_cache:
          paths: [backend/node_modules]
          key:  backend-build   
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:           
          name: Run backend test
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]      
      - run:          
          name: Run backend test
          command: |
            cd backend
            npm install
            npm run test    
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run: 
          name: scan frontend dependencies
          command: |                 
            cd frontend
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
          name: scan backend dependencies
          command: |
            cd backend
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force  
            exit 1            
  deploy:
    executor:
      name: node/default #hello
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: general
          event: fail
          template: basic_fail_1

workflows:
  default:
    jobs:
      - build-frontend #name
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend] 
      - scan-frontend:
          requires: [build-frontend]   
      - scan-backend:
          requires: [build-backend] 
      - deploy:
          context: slack-secrets           
